function test1(f,x) {
    try 1 + f(x) catch z {
        @println("- I caught this exception: ",z);
        if @is_error(z) {
            @println("- It's an error");
            @println("- The value of the error is: ",@string(z));
            "caught!"
        }
    }
}

function test2(x) {
    1 / x
}

function test3(x) {
    "hello" < x
}

@test("test1(test2,2)",1.5);
@println();
@test("test1(test2,0)","caught!");
@println();
@test("test1(test3,10)","caught!"); 
